#!/usr/bin/env bash

# Install clip-shell-utilities as a git submodule in the current repository
# This script is designed to be readable and safe to inspect before running.
#
# Usage:
#   curl https://raw.githubusercontent.com/adarro/clip-shell-utilities/main/install_sub.sh | sh
#   ./install_sub.sh
#
# This script should be run from the root of a git repository.

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============= Helper Functions =============

log_error() {
    echo -e "${RED}✗ Error:${NC} $1" >&2
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_step() {
    echo -e "${BLUE}──${NC} $1"
}

# ============= Validation =============

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    log_error "Not in a git repository. Please run this script from the root of a git repository."
    exit 1
fi

# Check if we're at the repository root
if [[ ! -f .git/config ]]; then
    log_error "Not at the repository root. Please run this script from the root of the repository."
    exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

log_info "Installing clip-shell-utilities to: $REPO_ROOT"
echo ""

# ============= Step 1: Add Submodule =============

log_step "Step 1: Adding git submodule"

if [[ -d clip-shell-utilities ]]; then
    log_warning "clip-shell-utilities directory already exists. Skipping submodule add."
else
    if git submodule add https://github.com/adarro/clip-shell-utilities.git clip-shell-utilities 2>&1; then
        log_success "Git submodule added"
    else
        log_error "Failed to add git submodule"
        exit 1
    fi
fi

echo ""

# ============= Step 2: Handle justfile =============

log_step "Step 2: Configuring justfile"

if [[ -f justfile ]]; then
    # Existing justfile - create import stub
    log_info "Found existing justfile"
    
    # Check if already has clipp module
    if grep -q "mod clipp" justfile; then
        log_warning "justfile already references 'clipp' module. Skipping configuration."
    elif grep -q "import.*clippstub" justfile; then
        log_warning "justfile already imports 'clippstub.just'. Skipping configuration."
    else
        # Create the stub file with instructions
        STUB_FILE="$REPO_ROOT/clippstub.just"
        
        cat > "$STUB_FILE" << 'STUBEOF'
# clip-shell-utilities Integration Guide
# ======================================
#
# This file was created by the clip-shell-utilities installer.
# Choose one of the methods below to integrate the module recipes.

# METHOD 1: Module Mode (Recommended for new projects)
# ────────────────────────────────────────────────────
# Add this line to your justfile:
#   mod clipp './clip-shell-utilities'
#
# Then reference recipes with 'clipp::recipe' prefix:
#   just clipp::url
#   just clipp::local
#   just clipp::test
#
# Advantages:
#   - Recipes keep their namespace (clipp::)
#   - Module can be updated independently
#   - Only shows up with 'just --list' when you ask for module recipes

# METHOD 2: Import Mode (For integrating into existing recipes)
# ─────────────────────────────────────────────────────────────
# Add this line to your justfile:
#   import 'clippstub.just'
#
# Then reference recipes directly:
#   just url
#   just local
#   just test
#
# Advantages:
#   - All recipes appear in 'just --list'
#   - Simpler names without 'clipp::' prefix
#   - Easier to integrate into existing workflows
#
# NOTE: File cleanup
#   - If using METHOD 1 (mod clipp): You can delete this file after adding the line
#   - If using METHOD 2 (import): Keep this file; it's a required dependency
#
# ============= Module Definition =============

mod clipp './clip-shell-utilities'
STUBEOF
        
        log_success "Created clippstub.just with integration instructions"
    fi
else
    # No existing justfile - create one with module
    JUSTFILE="$REPO_ROOT/justfile"
    
    cat > "$JUSTFILE" << 'JUSTEOF'
# Justfile - Task automation
# Generated by clip-shell-utilities installer
# Repository: https://github.com/adarro/clip-shell-utilities

mod clipp './clip-shell-utilities'

# First-time setup: install scripts and run basic check
@firstrun:
    @just clipp::setup
    @just clipp::check
JUSTEOF
    
    log_success "Created new justfile with clipp module"
fi

echo ""

# ============= Success Message =============

log_success "Installation complete!"
echo ""

if [[ -f justfile ]]; then
    if grep -q "mod clipp" justfile || grep -q "import.*clippstub" justfile; then
        log_info "Your justfile is ready to use."
        echo ""
        echo "Next steps:"
        echo "  1. Review the changes: git status"
        echo "  2. Test the setup: just clipp::help"
        echo "  3. Run first-time setup: just firstrun (if you created a new justfile)"
        echo ""
        echo "Available recipes:"
        echo "  just clipp::url              - Open URL from clipboard"
        echo "  just clipp::local            - Open local directory from clipboard"
        echo "  just clipp::test             - Run module tests"
        echo "  just clipp::help             - Show all available recipes"
    fi
else
    log_info "Integration complete. Current directory: $REPO_ROOT"
fi

echo ""
log_info "For more information, see: clip-shell-utilities/README.md"
